apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: currency-sink-bind
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: currency-source
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kafka-producer